- microdraw.js
This is an alternative implementation of multi-image undo that uses a single undo queue, tying each previous editing state to a specific image's annotations (implemented as a paper.js project). This means that actions taken on a slice can be undone while viewing another slice.
The undo operation should now assign the newly recreated paths to the correct project.
It is not clear to me which is really the better design from a user's point of view. Feel free to evaluate and use whichever one you prefer.
> Alternative multi-image undo with a single undo queue.

- microdraw.js
Try this and see if it is preferable.
> Switch to the slice where an undo operation will be performed.

- public/js/microdraw-ws.js
Partial fix for #69 
There is much more than 447 complaints from Eslint !
> Update microdraw-ws.js (fix #69)

- microdraw.js
I did not setup the environment so feel free to reject the pull. The  Converted all instances of $.Deferred to es6 promises (did not convert any in the public folder, assuming that is integrated into a build process).
For makeSVGInline method, you may want to look at where you are resolving. It is contained in the each loop, but you may want to do it outside of the for loop?
> fixes #82 - converted jquery promises to es6

- controller/data/data.controller.js
Fix object destructuring linting on #70
> Fix object destructuring linting

- README.md
- public/js/configuration.json.example
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> set directly useDatabase to true in the example file

- .gitignore
- public/js/microdraw.js
- public/js/tools/draw.js
- public/js/tools/drawLine.js
- public/js/tools/drawPolygon.js
- public/js/tools/flipRegion.js
- public/js/tools/screenshot.js
- public/js/tools/select.js
- public/js/tools/splitRegion.js
- public/js/tools/toBezier.js
- public/js/tools/toPolygon.js
- views/data.mustache
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> Make microdraw.js more eslint compliant

- .circleci/config.yml
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> instantiate config files in circleci

- app.js
- controller/data/data.controller.js
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> app soft fails when github-keys.json is absent

- views/index.mustache
so that app started on other hosts than http://microdraw.pasteur.fr will also work, removal of a link that seems to be dead
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> modifying links on the index.mustache 

- host.js
Existing behaviour will log `Server queried` regardless if the request was successful. The staged change will log `Server query error` as well as the error.
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* closeMenu …
> logging in hostjs are now more meaningful

- app.js
When discussing the issues surround failed CI with @pglock , we realised connection to mongodb has an unhandled promise rejection. This PR should allow the promise rejection to be more transparent.
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* …
> added explicit process exit when mongodb fails to connect

- package-lock.json
- public/js/microdraw.js
PR #121 broke a number of tools, because they were not imported in `microdraw.js`. This PR aims to fix this.
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> fixing missing tools

- app.js
- public/js/microdraw.js
tile source as a function broke as of https://github.com/r03ert0/microdraw/commit/ad81d279d35aebde2f4ede702363a5a584ebf940#diff-3d7a78a9aabf13427d220b45bb725fb6L2307 . 
this PR aims to fix this. 
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* …
> fix tile source as function

- public/js/configuration.json.example
- public/js/microdraw.js
- views/data.mustache
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> Preconfigure tools

- .circleci/config.yml
- .gitignore
- README.md
- app.js
- package-lock.json
- package.json
- public/js/base.js.example
- public/js/microdraw.js
- public/js/tools/save.js
- views/data.mustache
- views/index.mustache
Refactoring the functionalities related to annotations. They are now controlled by the `save.js` tool, which can be swapped should users have different backends/ allow easier extension to annotation saving and loading. 
During the refactoring, I noticed that `base.js` would no longer be necessary, as it was originally used solely for the front end to communicate with db. With `node` as the backend, most annotaiton api calls are made via `node-express`. 
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* …
> Tidying save load functionality

- app/views/data.mustache
- app/views/index.mustache
- app/views/partials/header.mustache
- app/views/partials/menu.mustache
Modularising the view templates, hopefully making it easier to be maintained. 
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> using partials for templating

- app/public/js/microdraw.js
minor bug fix that prevented tools loading to be done before loading microdraw.
Current behaviour: `Promise.all( [ [ promise1, promise2 ] ] )`. which resolves instantly
Expected behaviour: `Promise.all( [ promise1, promise2] )` which resolves when all the inner promises resolves.
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate …
> bug fix: blocking load all preset tools

- app/public/js/microdraw.js
some of our tools would benefit greatly by able to listen to the scrolling event. 
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> adding scroll handler, allowing tools to take advantage of scroll events

- .circleci/config.yml
- README.md
- app/auth/auth.js
- package.json
Use `connect-mongo` to store session (+ passport login session). The default in memory storage of `express-session` is [intended for developing usage only](https://www.npmjs.com/package/express-session#api):
> Warning The default server-side session storage, MemoryStore, is purposely not designed for a production environment. It will leak memory under most conditions, does not scale past a single process, and is meant for debugging and developing.
this PR aims to save the user session in mongodb, under the collection `session`. 
This has the added benefit that on application restart, it no longer wipes user's login status.
---
* **GESTURES**
* **KEYS**
* cmd z undoes
to be completed (maybe it is implemented and working for all functions, …
> using connect mongo for user session

- .gitignore
- app/auth/auth.js
- app/views/partials/menu.mustache
Current behaviour: if mongo store fails to connect to a mongo store, it will throw exception and process will end.
This PR provides an in memory fallback, if mongo store fails to connect
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* screenshot …
> provide memory fallback for mongostore

- .circleci/config.yml
- app/app.js
- app/auth/local.spec.js
- app/db/db.js
- app/db/db.spec.js
- test.js
Also changed circleci config to take advantage of docker images bundled with browser
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> pr add better feedback when mongo connection fails

- app/routes/routesExtensions.js
node-fetch was removed as a dependency awhile ago, but one of the module still used node-fetch. 
This PR should fix this. 
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> bugfix: use request instead of fetch for getTile

- app/public/js/microdraw.js
- app/public/js/tools/openMenu.js
- app/views/data.mustache
bugfix: populate layer opacity (partially fixes #162)
bugfix: openmenu button now works
bugfix: remove unopened style tag
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> pr: opacity slider/input now populate with correct value + menu open should now work

- app/auth/github.js
- app/db/db.js
- app/db/db.spec.js
fixing github login
---
* **GESTURES**
* **KEYS**
* cmd z undoes
* home button
* zoomIn tool
* zoomOut tool
* left arrow
* right arrow
* select tool
* draw tool
* rotate tool
* flip tool
* toBezier
* copy tool
* paste tool
* save tool
* delete tool
* undo tool
> bugfix: github login

- .circleci/config.yml
- PULL_REQUEST_TEMPLATE.md
- app/auth/local.spec.js
- app/controller/api/api.spec.js
- app/controller/api/index.js
- app/db/db.spec.js
- app/public/js/tools/save.js
- app/routes/routeExtensions.spec.js
- app/routes/routes.js
- package-lock.json
- package.json
- test/mocha.test.js
> Fix save load slice nr

- app/routes/routeExtensions.spec.js
- app/routes/routesExtensions.js
> bugfix: should hopefually fix #174

- app/public/js/microdraw.js
- app/public/js/tools/save.js
- package.json
- test.js
- test/e2e/save.spec.js
> Pr save path deselects path first

- app/auth/token.js
- app/auth/token.spec.js
- app/routes/routes.js
> debug: fix token auth, only fires in api routes

- app/app.js
> chore: remove uncessary require

- app/auth/auth.spec.js
- package.json
Re: mocha vuln: https://github.com/mochajs/mocha/releases/tag/v6.1.4
> fix mocha vuln, fix auth test

- app/controller/project/project.controller.js
- app/db/db.js
- app/public/js/microdraw.js
- app/views/data.mustache
- app/views/project.mustache
- app/views/projectSettings.mustache
> working on project management, fix default zoom bug

- app/controller/project/project.controller.js
- app/db/db.js
- app/public/css/projectSettings-style.css
- app/public/js/microdraw.js
- app/routes/routes.js
- app/views/projectNew.mustache
- app/views/projectSettings.mustache
> implement autocomplete

- app/controller/search/index.js
- app/controller/search/search.controller.js
- app/views/project.mustache
- app/views/projectNew.mustache
- app/views/projectSettings.mustache
- app/views/user.mustache
> use CDN for libraries, add search to API

- app/controller/project/project.controller.js
- app/db/db.js
- app/views/projectSettings.mustache
> implement project import through csv

- app/controller/project/project.controller.js
- app/db/db.js
> change upsertproject function to handle the insert part without error

- app/views/projectSettings.mustache
> use textarea instead of input for project description

- app/controller/project/index.js
- app/controller/project/project.controller.js
- app/db/db.js
- app/views/projectSettings.mustache
- app/views/user.mustache
> implement DeleteProject; fix AddProject in user page

- README.md
- app/auth/auth.spec.js
- app/auth/token.js
- app/controller/api/api.spec.js
- app/controller/api/index.js
- bin/docker-compose.yml
- package-lock.json
- test/mocha.test.util.js
- [ x `test_screenshots` generates the same test pictures in `test` as there were in `test/reference` and does not show any errors
> feat: added API tests

- package-lock.json
- package.json
updated from bson=1.0.4 to bson>=1.0.5
> fix bson vulnerability

- app/controller/api/api.spec.js
- app/controller/api/index.js
added tests on malformed json
**please note** the `validateJson` method is rewritten slightly:
https://github.com/r03ert0/microdraw/blob/bugfix_fixtests/app/controller/api/index.js#L59
in order to satisfy the test json:
https://github.com/r03ert0/microdraw/blob/bugfix_fixtests/app/controller/api/api.spec.js#L155
I took the json in `api.spec.js` from https://github.com/r03ert0/microdraw/issues/186#issuecomment-485735157
> fixes tests

- app/app.js
- app/controller/api/index.js
- app/controller/data/data.controller.js
- app/db/db.js
- app/public/css/project-style.css
- app/public/js/microdraw.js
- app/public/js/tools/draw.js
- app/public/js/tools/save.js
- app/views/project.mustache
- app/views/projectSettings.mustache
- app/views/user.mustache
- package-lock.json
- package.json
> several improvements on project handling plus minor bug fixing

- app/controller/api/api.spec.js
> update error messages in test

- app/controller/api/api.spec.js
- app/controller/api/index.js
> rewrote tests for api

- app/views/projectSettings.mustache
> implement export to csv

- app/public/js/tools/findContours.js
- app/public/js/tools/save.js
> cancel button in findContours

- .circleci/config.yml
- app/auth/auth.js
- app/auth/local.spec.js
- app/db/db.js
- app/db/db.spec.js
- test/e2e/save.spec.js
> bugfix: requiring explicit setting of test db path

- app/public/img/redo.svg
- app/public/js/configuration.json
- app/public/js/tools/redo.js
> add redo button

- .circleci/config.yml
- app/controller/api/api.spec.js
- package.json
- test.js
Changes to `api/index.js` broke a few tests. This PR should address the change and fix the tests.
> Fix mocha tests
